import type { PlaygroundOperation } from './types';

export const playgroundOperations: PlaygroundOperation[] = [
  {
    id: 'ping',
    category: 'Connectivity',
    title: 'Ping',
    summary: 'Verify transport reachability and request-response health.',
    fields: [],
  },
  {
    id: 'get',
    category: 'Key Value',
    title: 'Get',
    summary: 'Read one key and return its current string value.',
    fields: [
      {
        key: 'key',
        label: 'Key',
        kind: 'text',
        description: 'The exact key to read.',
        placeholder: 'app:theme',
      },
    ],
  },
  {
    id: 'set',
    category: 'Key Value',
    title: 'Set',
    summary: 'Write a value with optional conditional and TTL modifiers.',
    fields: [
      {
        key: 'key',
        label: 'Key',
        kind: 'text',
        description: 'The destination key.',
        placeholder: 'playground:message',
      },
      {
        key: 'value',
        label: 'Value',
        kind: 'textarea',
        description: 'The string value to write.',
        placeholder: 'Hello from the Vaylix SDK playground.',
      },
      {
        key: 'ttlSeconds',
        label: 'TTL Seconds',
        kind: 'number',
        description: 'Optional expiration in whole seconds.',
        min: 1,
      },
      {
        key: 'ttlMilliseconds',
        label: 'TTL Milliseconds',
        kind: 'number',
        description: 'Optional expiration in milliseconds.',
        min: 1,
      },
      {
        key: 'keepTtl',
        label: 'Keep TTL',
        kind: 'switch',
        description: 'Preserve the existing TTL when overwriting.',
      },
      {
        key: 'onlyIfMissing',
        label: 'Only If Missing',
        kind: 'switch',
        description: 'Write only when the key does not already exist.',
      },
      {
        key: 'onlyIfExists',
        label: 'Only If Exists',
        kind: 'switch',
        description: 'Write only when the key already exists.',
      },
      {
        key: 'returnPrevious',
        label: 'Return Previous',
        kind: 'switch',
        description: 'Return the previous value instead of a plain OK.',
      },
    ],
  },
  {
    id: 'del',
    category: 'Key Value',
    title: 'Delete',
    summary: 'Delete one or more keys and return the removal count.',
    fields: [
      {
        key: 'keys',
        label: 'Keys',
        kind: 'tags',
        description: 'Comma-separated list of keys to delete.',
        placeholder: 'playground:message,playground:count',
      },
    ],
  },
  {
    id: 'exists',
    category: 'Key Value',
    title: 'Exists',
    summary: 'Check whether a key currently exists.',
    fields: [
      {
        key: 'key',
        label: 'Key',
        kind: 'text',
        description: 'The key to check.',
        placeholder: 'playground:message',
      },
    ],
  },
  {
    id: 'mget',
    category: 'Key Value',
    title: 'MGet',
    summary: 'Read several keys in one SDK call.',
    fields: [
      {
        key: 'keys',
        label: 'Keys',
        kind: 'tags',
        description: 'Comma-separated keys to fetch.',
        placeholder: 'app:theme,app:region',
      },
    ],
  },
  {
    id: 'mset',
    category: 'Key Value',
    title: 'MSet',
    summary: 'Write a full object of key/value entries.',
    fields: [
      {
        key: 'entries',
        label: 'Entries JSON',
        kind: 'json',
        description: 'JSON object of string keys to string values.',
        placeholder: '{"playground:one":"alpha","playground:two":"beta"}',
      },
    ],
  },
  {
    id: 'expire',
    category: 'Key Value',
    title: 'Expire',
    summary: 'Attach or replace a TTL in whole seconds.',
    fields: [
      {
        key: 'key',
        label: 'Key',
        kind: 'text',
        description: 'Key that should expire.',
        placeholder: 'playground:message',
      },
      {
        key: 'seconds',
        label: 'Seconds',
        kind: 'number',
        description: 'TTL in seconds.',
        placeholder: '60',
        min: 1,
      },
    ],
  },
  {
    id: 'ttl',
    category: 'Key Value',
    title: 'TTL',
    summary: 'Read the server-reported TTL for a key.',
    fields: [
      {
        key: 'key',
        label: 'Key',
        kind: 'text',
        description: 'Key to inspect.',
        placeholder: 'playground:message',
      },
    ],
  },
  {
    id: 'persist',
    category: 'Key Value',
    title: 'Persist',
    summary: 'Remove any TTL from a key.',
    fields: [
      {
        key: 'key',
        label: 'Key',
        kind: 'text',
        description: 'Key whose TTL should be removed.',
        placeholder: 'playground:message',
      },
    ],
  },
  {
    id: 'info',
    category: 'Observability',
    title: 'Info',
    summary: 'Return the server key/value info map.',
    fields: [],
  },
  {
    id: 'health',
    category: 'Observability',
    title: 'Health',
    summary: 'Return machine-oriented node health fields.',
    fields: [],
  },
  {
    id: 'showCluster',
    category: 'Cluster',
    title: 'Show Cluster',
    summary: 'Inspect role, term, leader, quorum, and membership state.',
    fields: [],
  },
  {
    id: 'showReplication',
    category: 'Cluster',
    title: 'Show Replication',
    summary: 'Inspect replication role, lag, and acknowledgement details.',
    fields: [],
  },
  {
    id: 'metrics',
    category: 'Observability',
    title: 'Metrics',
    summary: 'Read numeric metrics returned by the SDK.',
    fields: [],
  },
  {
    id: 'metricsProm',
    category: 'Observability',
    title: 'Metrics Prom',
    summary: 'Read Prometheus exposition text.',
    fields: [],
  },
  {
    id: 'clusterJoin',
    category: 'Cluster',
    title: 'Cluster Join',
    summary: 'Add or update a member in the cluster membership set.',
    fields: [
      {
        key: 'nodeId',
        label: 'Node ID',
        kind: 'text',
        description: 'Stable cluster node identifier.',
        placeholder: 'node-2',
      },
      {
        key: 'address',
        label: 'Address',
        kind: 'text',
        description: 'Peer address in host:port form.',
        placeholder: '10.0.0.12:9173',
      },
    ],
  },
  {
    id: 'clusterRemove',
    category: 'Cluster',
    title: 'Cluster Remove',
    summary: 'Remove a member by node ID.',
    fields: [
      {
        key: 'nodeId',
        label: 'Node ID',
        kind: 'text',
        description: 'Member node ID to remove.',
        placeholder: 'node-2',
      },
    ],
  },
  {
    id: 'promoteFollower',
    category: 'Cluster',
    title: 'Promote Follower',
    summary: 'Run the leader-only promotion command.',
    fields: [],
  },
  {
    id: 'pauseReplication',
    category: 'Cluster',
    title: 'Pause Replication',
    summary: 'Pause follower replication streams.',
    fields: [],
  },
  {
    id: 'resumeReplication',
    category: 'Cluster',
    title: 'Resume Replication',
    summary: 'Resume follower replication streams.',
    fields: [],
  },
  {
    id: 'transactionExec',
    category: 'Transactions',
    title: 'Transaction Exec',
    summary: 'Queue a transaction script and commit it through exec().',
    fields: [
      {
        key: 'steps',
        label: 'Transaction Steps JSON',
        kind: 'json',
        description:
          'Array of steps. Supported ops: get, set, del, exists, expire, ttl, persist.',
        placeholder:
          '[{"op":"set","key":"playground:tx","value":"ok"},{"op":"get","key":"playground:tx"}]',
      },
    ],
  },
];
